### ISSUE TITLE
Désactiver les menus "Try it" quand l'URI de base n'est pas définie

### ISSUE THREAD

**Issue by jageay** [SNCF-SIV/api-console#22]
Les services ne peuvent être "essayés" quand la propriété `baseUri` n'est pas définie. Dans la précédente version de la console, les menus "Try it" étaient grisés dans ce cas.

**Comment by npayneau** [comment]
Bonjour Jean-Alain,

Pour info, nous allons migrer prochainement vers la version 2.0.4 du stream master implémentant cette fonctionnalité.

Nicolas

**Comment by npayneau** [comment]
Jean-Alain,

Nous avons fait la release 2.0.4.SNCF embarquant cette fonctionnalitée. L'issue est close
